# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thegun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='枪的名字')),
                ('capacity', models.IntegerField(verbose_name='弹夹容量')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='生产日期')),
            ],
            options={
                'db_table': '枪',
                'verbose_name': '表名',
            },
        ),
    ]
