# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firecart',
            name='speed',
            field=models.IntegerField(db_column='myspeed', default=30, verbose_name='时速'),
        ),
    ]
