# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_02', '0002_auto_20180814_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firecart',
            options={'verbose_name': '火车类'},
        ),
        migrations.AlterModelTable(
            name='firecart',
            table='huocart',
        ),
    ]
